import Head from "next/head";
import styles from "@/styles/home.module.css";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1>Playground index</h1>
                <a href="/binaryTree">Binary Tree</a>
                <a href="/graph">Graph (console)</a>
                <a href="/balls">Bouncing balls</a>
                <a href="/steeringBehaviour">Ball ecosystem</a>
                <a href="/aStarSearch"> A* Search</a>
                <a href="/maze">Maze</a>
                <a href="/travelingSalesMan">Traveling Salesman</a>
                <a href="/geneticTravelingSalesMan">
                    TravelingSalesman with genetic algorithm
                </a>
                <a href="/linearRegression">Linear Regression</a>
                <a href="/doodle">Doodle</a>
                <a href="/test">Test</a>
            </main>
        </>
    );
}
